DOMAIN = "hue_smooth_dimmer"

SERVICE_RAISE = "raise"
SERVICE_LOWER = "lower"
SERVICE_STOP = "stop"

DEFAULT_SWEEP_TIME = 5
DEFAULT_MAX_BRIGHTNESS = 100.0
DEFAULT_MIN_BRIGHTNESS = 0.0

STALE_BRIGHTNESS_GUARD_SECONDS = 15
